version: '3.5'
name: nestjs_test_app

networks:
  inside_net:
    name: inside_net
    driver: bridge

services: 
  app:
    build: ./
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - 'APP_PORT=${APP_PORT}'
      - 'DB_HOST=postgres_db'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'REDIS_HOST=redis'
    depends_on:
      - postgres_db
      - redis
    networks:
      - inside_net

  postgres_db:
    image: postgres:16.0
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment: 
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    networks:
      - inside_net

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - ./redis_data:/data
    networks:
      - inside_net